### ISSUE TITLE
Group sources and resources nodes under sourceSet name

### ISSUE THREAD

**Issue by gallardo** [kelemen/netbeans-gradle-project#193]
I have imported a project that defines several (many) sourceSets for corresponding tasks. The current project tree view under these circumstances is almost useless. It'd be very convenient to group the nodes by their sourceSet.

Take the following `build.gradle` as example:

    apply plugin: 'java'

    sourceCompatibility = '1.8'
    [compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

    ['a','b','c','d','e','f','g'].each { moduleName ->
        sourceSets.create('org.example.gradlemodule.' + moduleName, {
                java.srcDir "src/main/java"
                resources.srcDir "src/main/resources"
            })

    }

The corresponding tree is very confusing:
![image](https://cloud.githubusercontent.com/assets/790448/7023977/d35ff5f2-dd39-11e4-979b-cb7526fa7271.png)

**Comment by kelemen** [comment]
In this example, grouping by source sets would "only" halve the number of nodes. Can you give a more specific example how you imagine the nodes to be displayed (with node titles and everything)?

**Comment by gallardo** [comment]
That's completely true, but in the last example, the script only defined one java `srcDir` and one resources `srcDir`. This could be different:

        sourceSets.create('org.example.gradlemodule.' + moduleName, {
                java.srcDir "src/main/java"
                java.srcDir "src/main/java2"
                resources.srcDir "src/main/resources"
                resources.srcDir "src/main/resources2"
            })

In this case, the tree is even uglier than the one before:
![image](https://cloud.githubusercontent.com/assets/790448/7025352/5eac8130-dd43-11e4-8a5b-e1aba22ac8e8.png)

There is one additional issue: the names displayed for each node alternate between

    $sourceSet.name/Java Packages in ...
and

    Resources [$sourceSet.name] in ...
The different indentation makes very hard to visually identify nodes of interest.

I think that if the nodes were grouped by their source set, it'd be much easier to find a module:
![image](https://cloud.githubusercontent.com/assets/790448/7025453/21d7a96e-dd44-11e4-97de-bddd17ab8a3a.png)

I would even suggest to hide the duplicated information from the node names:
![image](https://cloud.githubusercontent.com/assets/790448/7025479/47700374-dd44-11e4-812e-637d22b82334.png)

**Comment by gallardo** [comment]
One more comment: if possible, the dependencies should also be placed under the corresponding module. But I'm pretty new in Gradle and I'm not sure that this even makes sense.

**Comment by kelemen** [comment]
I see, I don't think this will make into the next release but probably into the one after. Also, there could be other ways to group the source roots, so I will consider those as well.

I don't understand your last comment. Dependencies are under the "Dependencies" node grouped by the source set they belong to (+ compile/provided/runtime). How else would you think it would be better?

**Comment by gallardo** [comment]
Great!

Following with the previous example, this is what I mean:
![image](https://cloud.githubusercontent.com/assets/790448/7027966/0bd6280c-dd53-11e4-915b-1634d343c534.png)


This is how it currently looks like in my current (real) project:
![image](https://cloud.githubusercontent.com/assets/790448/7027928/c3734a04-dd52-11e4-873e-5410e933f641.png)

I always have to scroll up and down when checking for dependencies, looking for classes, etc.

**Comment by kelemen** [comment]
Why do you have to check dependencies often? I mean, I never do, just added the dependencies node for completness sake. To be honest, I rarely use the sources node directly, if I have to go to a specific node, I just click "Select in projects" on the editor tab.

**Comment by gallardo** [comment]
Unfortunatelly, I cannot get code completion for the jsps (see https://github.com/hildo/netbeans-gradle-javaee-project/issues/16). This requires me to check the dependencies more often than I'd wish. (I hope I find a workaround soon.)

With regard to the "Select in projects" feature, this only works for files already open.

But I agree, I have never missed the dependencies node until I began working with a CMS project. Notice that in my case, the CMS webapp even pre-compiles and adds to the standard servlet API, what makes code completion in some cases even imposible without further NetBeans extensions. (That is, I'm afraid that I won't ever get full code completion support.)

**Comment by kelemen** [comment]
In what directory are your JSP files? It might be important to know to solve the code completion issue.

By the way, to open files I use <kbd>Ctrl+O</kbd> or <kbd>Alt+Shift+O</kbd>, those are much more convenient than looking up in some directory.

Code completion is probably solveable regardless how you add your dependencies. The worst case is that you have to tweak your build script to lie to NetBeans about dependencies. That is, you do anything under the condition `project.hasProperty('evaluatingIDE') && project.property('evaluatingIDE') == 'NetBeans'` (whatever you do under this condition will only be visible to NetBeans and only for model loading).

**Comment by gallardo** [comment]
For the last try, I created a new jsp in a new gradle project using all defaults. This was `src/main/webapp`. But I also tried setting the `webAppDirName`. The netbeans-gradle-javaee plugin does recognize the folder, but I get no code completion. 

Thank you for the shortcuts. I'm puzzled about how much I oversee when using NetBeans. I'm looking forward to coming back to my workplace and test them!

And thank you also for the last hint. It looks very promising.

**Comment by kelemen** [comment]
There might be an awkward workaround (I'm not sure if it works but it is good to know if it does):

    if (project.hasProperty('evaluatingIDE') && project.property('evaluatingIDE') == 'NetBeans') {
        sourceSets.main.java.srcDir('webapp')
    }

The problem with this is that you will have two nodes for the webapp directory but if it helps, I think I know what is the problem.

**Comment by gallardo** [comment]
Unfortunately, the workaround doesn't help. (To not double-post, see https://github.com/hildo/netbeans-gradle-javaee-project/issues/16#issuecomment-90838905)

PS: Thanks again for the navigation shortcut. It's really valuable.

**Comment by kelemen** [comment]
This is mostly done in master. Can you build the plugin from the sources and try it? (One caveat I'm working on is that the source set node only has error badge if you restart NB after changing the source set display mode). You can change how the sources are displayed in the global settings: Misc/Gradle/Appearance.

**Comment by kelemen** [comment]
I have fixed the issue I was having with this feature. Can you try and confirm if this is what you expect?

**Comment by gallardo** [comment]
First try:

```
  Stack trace:
    java.lang.NullPointerException
    	at org.netbeans.gradle.project.model.NbGenericModelInfo.getSettingsFileAsFile(NbGenericModelInfo.java:50)
    	at org.netbeans.gradle.project.model.NbGenericModelInfo.tryGetSettingsFileObj(NbGenericModelInfo.java:84)
    	at org.netbeans.gradle.project.model.GradleModelCache.tryCreateKey(GradleModelCache.java:101)
    	at org.netbeans.gradle.project.model.GradleModelCache.replaceEntry(GradleModelCache.java:151)
    	at org.netbeans.gradle.project.model.GradleModelLoader.introduceLoadedModel(GradleModelLoader.java:410)
    	at org.netbeans.gradle.project.model.GradleModelLoader.introduceProjects(GradleModelLoader.java:432)
    	at org.netbeans.gradle.project.model.GradleModelLoader.loadModelWithProgress(GradleModelLoader.java:517)
    	at org.netbeans.gradle.project.model.GradleModelLoader.access$700(GradleModelLoader.java:68)
    	at org.netbeans.gradle.project.model.GradleModelLoader$6.run(GradleModelLoader.java:342)
    	at org.netbeans.gradle.project.tasks.GradleDaemonManager.runNonBlockingGradleTask(GradleDaemonManager.java:36)
    	at org.netbeans.gradle.project.tasks.GradleDaemonManager.access$100(GradleDaemonManager.java:23)
    	at org.netbeans.gradle.project.tasks.GradleDaemonManager$2.execute(GradleDaemonManager.java:126)
    	at org.jtrim.concurrent.AbstractTaskExecutorService$FunctionWrapper.execute(AbstractTaskExecutorService.java:270)
    	at org.jtrim.concurrent.AbstractTaskExecutorService$TaskOfAbstractExecutor.execute(AbstractTaskExecutorService.java:340)
    	at org.jtrim.concurrent.Tasks$RunOnceCancelableTask.execute(Tasks.java:342)
    	at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.runTask(SingleThreadedExecutor.java:919)
    	at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.access$1200(SingleThreadedExecutor.java:898)
    	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.executeTask(SingleThreadedExecutor.java:815)
    	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.processQueue(SingleThreadedExecutor.java:827)
    	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.run(SingleThreadedExecutor.java:861)
    	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$1.run(SingleThreadedExecutor.java:453)
    	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gallardo** [comment]
This is the NetBeans view "Projects":

![screenshot - 15 05 2015 - 15 10 53](https://cloud.githubusercontent.com/assets/790448/7653275/c1032304-fb14-11e4-9278-75bbaa69f30b.png)

**Comment by kelemen** [comment]
I have fixed the NPE you were having, can you try it again?

**Comment by gallardo** [comment]
Yeah! This is so much better!

![screenshot - 15 05 2015 - 15 47 35](https://cloud.githubusercontent.com/assets/790448/7653933/c4a75e58-fb19-11e4-88ad-50400382dec9.png)

I'm still getting a NPE after NetBeans restart. I cannot identify any misbehaviour, though.

```
java.lang.NullPointerException
	at org.netbeans.gradle.project.model.NbGenericModelInfo$SerializedFormat.<init>(NbGenericModelInfo.java:167)
	at org.netbeans.gradle.project.model.NbGenericModelInfo.writeReplace(NbGenericModelInfo.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at java.io.ObjectStreamClass.invokeWriteReplace(ObjectStreamClass.java:1075)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1136)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.netbeans.gradle.project.util.SerializationUtils2.serializeToFile(SerializationUtils2.java:15)
	at org.netbeans.gradle.project.model.MultiFileModelCache.saveGradleModel(MultiFileModelCache.java:110)
	at org.netbeans.gradle.project.model.MultiFileModelCache.saveGradleModel(MultiFileModelCache.java:53)
	at org.netbeans.gradle.project.model.MultiFileModelCache.saveGradleModels(MultiFileModelCache.java:47)
[catch] at org.netbeans.gradle.project.model.GradleModelLoader.saveToPersistentCache(GradleModelLoader.java:398)
	at org.netbeans.gradle.project.model.GradleModelLoader.introduceProjects(GradleModelLoader.java:433)
	at org.netbeans.gradle.project.model.GradleModelLoader.loadModelWithProgress(GradleModelLoader.java:517)
	at org.netbeans.gradle.project.model.GradleModelLoader.access$700(GradleModelLoader.java:68)
	at org.netbeans.gradle.project.model.GradleModelLoader$6.run(GradleModelLoader.java:342)
	at org.netbeans.gradle.project.tasks.GradleDaemonManager.runNonBlockingGradleTask(GradleDaemonManager.java:36)
	at org.netbeans.gradle.project.tasks.GradleDaemonManager.access$100(GradleDaemonManager.java:23)
	at org.netbeans.gradle.project.tasks.GradleDaemonManager$2.execute(GradleDaemonManager.java:126)
	at org.jtrim.concurrent.AbstractTaskExecutorService$FunctionWrapper.execute(AbstractTaskExecutorService.java:270)
	at org.jtrim.concurrent.AbstractTaskExecutorService$TaskOfAbstractExecutor.execute(AbstractTaskExecutorService.java:340)
	at org.jtrim.concurrent.Tasks$RunOnceCancelableTask.execute(Tasks.java:342)
	at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.runTask(SingleThreadedExecutor.java:919)
	at org.jtrim.concurrent.SingleThreadedExecutor$QueuedItem.access$1200(SingleThreadedExecutor.java:898)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.executeTask(SingleThreadedExecutor.java:815)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.processQueue(SingleThreadedExecutor.java:827)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$Worker.run(SingleThreadedExecutor.java:861)
	at org.jtrim.concurrent.SingleThreadedExecutor$Impl$1.run(SingleThreadedExecutor.java:453)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kelemen** [comment]
I have fixed this NPE as well. This last NPE prevents the persistent cache from working.

**Comment by gallardo** [comment]
Great job! I confirm that it's fixed.

**Comment by gallardo** [comment]
One last question: wouldn't it make sense to list the dependencies under their sourceSet node? (I'm still pretty new to gradle, so this could make no sense at all):

![screenshot - 15 05 2015 - 16 45 10](https://cloud.githubusercontent.com/assets/790448/7655188/214a3542-fb22-11e4-912a-fdafc5d9cb2b.png)

**Comment by gallardo** [comment]
Although dependency configurations and source sets are probably not necessarily related, to me it would make more sense...

**Comment by kelemen** [comment]
Structurally, it makes sense because dependencies belong to a source set. However, they waste space there because in the majority cases, you don't need that node.

**Comment by gallardo** [comment]
I guess this is a matter of taste and I can happily live with the current presentation. Thanks for your support!

**Comment by joebowbeer** [comment]
If java.srcDirs and resources.srcDirs both point to 'src' as they sometimes do, I'm seeing the Java files listed twice, once in Source Packages src and once in Other Packages src.

I don't think this should be happening because the "resources" source set is defined to contain only resources, excluding any .java files found in the resource source directories:

http://gradle.org/docs/current/userguide/java_plugin.html

Is the fact that the .java files are showing up in their resources-related source set an existing bug or a regression (perhaps related to this issue #193)?

By the way, it is not uncommon for the java.srcDirs and resources.srcDirs to be equivalent, or for the resources dirs to also contain Java source files. This is now common in Android projects that are migrated to Gradle, using the boilerplate:

sourceSets {
  main {
    manifest.srcFile 'AndroidManifest.xml'
    java.srcDirs = ['src']
    jniLibs.srcDirs = ['libs']
    resources.srcDirs = ['src']
    aidl.srcDirs = ['src']
    renderscript.srcDirs = ['src']
    res.srcDirs = ['res']
    assets.srcDirs = ['assets']
  }
}

**Comment by kelemen** [comment]
@joebowbeer Can you open a new issue describing what exactly you want? (I don't think what you say has anything to do with this rfe)

**Comment by joebowbeer** [comment]
#207

**Comment by gallardo** [comment]
I'm recovering my previous question because I have lots of distracting red flags (`package does not exist`) throughout the project, inspite the project building without problems from the command line.
> wouldn't it make sense to list the dependencies under their sourceSet node?

I have a [build script](https://github.com/alkacon/opencms-core/blob/build_9_5_2/build.gradle) that declares many source sets, for some of which it even explicitly set their classpaths. (To me, this looks like a bad smell in the code, but I'm still a gradle rookie, so I'm cautious with my judgements.) The [Gradle Java plugin](https://docs.gradle.org/current/userguide/java_plugin.html) creates for each source set two configurations and three tasks.

To exemplarize my problem, say I have created source set `X`, gradle will create two configurations `XCompile` and `XRuntime`, and three tasks `compileXJava`, `processXResources` and `xClasses`. Now, I manually set `sourceSets.x.compileClasspath= files("$buildDir/classes/y")` in my build script.

What I'd like as programmer without disposition (or time) to learn gradle in every detail is that NetBeans lets me know  what dependencies will apply to compile a given source file under a source set node (as a plus, it'd be also interesting to know what are its runtime dependencies). And I'd love to be able to right click in the source set node and be offered the `compileXJava`, `processXResources` or `xClasses` task that the Gradle Java plugin should have created.

In my case, instead a tree like:

```
project
+ Main
+ Test
+ ...
+ Components
|   + Java in [java]
|   + Java in [src-components]
|   + Resources in [resources]
|   + Resources in [src-components]
+ ...
+ Dependencies
|   + Compile for components
|        + ant-1.8.4.jar
|        + ant-contrib-1.0b3.jar
|        + ...
|   + Compile for main
|   + Runtime for ...
+ Build Scripts
```

something like this would be much more helpful:
```
project
+ Main
+ Test
+ ...
+ Components   // this is the source node name
|    + Java            // property 'sourceSet.components.java'
|         + /java
|         + /src-components
|    + Resources
|         + /resources
|         + /src-components
|    + Dependencies
|         + whatever libraries defined in "componentsCompile"
|         + compile
|              + additional files from the "sourceSet.components.compileClasspath"
|         + runtime
|              + additional files from the "sourceSet.components.runtimeClasspath"
+ more source set nodes
+ ...  // No global "Dependencies" node
+ Build Scripts
```

Does this make sense?


<sup>I'm sorry if this is a silly question, but I'm still struggling with the different gradle concepts and the external complex build script.</sup>

**Comment by kelemen** [comment]
The compileXJava in the context menu seems reasonable. However, I don't like the dependencies under the source set node (even if logically it would go there) because for most users it is just a noise (my guess is that you will stop caring about the dependencies node as well after some time). Altough putting at least the project dependencies in the context menu of the source set node seems fine.

**Comment by gallardo** [comment]
Thank you @Kelemen
>  (my guess is that you will stop caring about the dependencies node as well after some time)

I'm not sure I'll stop caring about this dependencies view :confused: for two reasons:
* At this moment it seems like I'm hitting a NetBeans bug<sup>(\*)</sup> but I'm neither sure, nor I know what the exact problem is<sup>(\*\*)</sup>. I think if I could quickly check the list of dependencies under the source node, it'd be easier to tell.
* I'd expect from NetBeans to provide me with a view that helps me to understand new projects. Resorting to the command line and querying gradle for properties, dependencies and detailled list of source sets is not very convenient<sup>(***)</sup>.

---
Notes
<sup>(\*)</sup> Many 'package not found' red flags throughout the source files, but the project compiles
<sup>(\*\*)</sup> Issue report will follow if applicable
<sup>(***)</sup> For anyone interested, I'm using the gradle snippet below to understand the nature of the source sets. The gradle reports don't surface all classpath dependencies.
```groovy
task listSourceSets <<{
    println "SourceSets:"
    sourceSets.each { sourceSet ->
        println sourceSet
        sourceSet.each {
            println "name: " + it.name
            println "output.classesDir: " + it.output.classesDir
            println "compileClasspath.asPath: " + it.compileClasspath.asPath
            println "java.name: " + it.java.name
            println "java.srcDirs: " + it.java.srcDirs
            println "resources.name: " + it.resources.name
            println "resources.srcDirs: " + it.resources.srcDirs
            println "-------------------------------------"
        }
    }
}
```

**Comment by kelemen** [comment]
So, if there was a "Sourceset info" in the context menu of the source set displaying an info dialog, how would you imagine it to look like?

**Comment by gallardo** [comment]
I'd expect a context menu similar to those from other NetBeans projects:

`Java->Java Application->Source Packages` context menu:
![image](https://cloud.githubusercontent.com/assets/790448/9517096/8834b7be-4cad-11e5-82ab-e9d9276bab04.png)
`Maven->Java Application->Source Packages` context menu:
![image](https://cloud.githubusercontent.com/assets/790448/9517120/c760a6a0-4cad-11e5-83b0-f5deb0731f6e.png)

`Java Web->Web Application->Source Packages` context menu:
![image](https://cloud.githubusercontent.com/assets/790448/9517162/26ade2b2-4cae-11e5-8bf8-83277ad52deb.png)

That is, I wouldn't expect the dependencies emerging in the context menu (I'd stick to them being listed under their source nodes). But if it must be, better than nowhere...

My suggestion:

    New >
    ----
    Paste
    ----
    Find...
    ----
    Dependencies >
        compile >
            configuration      // configuration dependencies
                org.slf4j:slf4j-simple:1.7.12
                ...
            classpath      // classpath dependencies (if I'm not wrong, currently 'provided')
                print.jar
                build/classes/main
        runtime >     // id. as compile
            ...
    ----
    CompileSourceSet
    History >
    ----
    Tools >

**Comment by kelemen** [comment]
The plugin doesn't know about configurations since I believe that once the artifacts of a configuration was added to a classpath, I can't tell where those dependencies came from. I can list all the configurations and resolve them but that might increase the loading time of some project considerably (for little benefit).

By the way "provided" is simply *compile - runtime*.

**Comment by gallardo** [comment]
Uhmmm...

> I can't tell where those dependencies came from

and
> "provided" is simply _compile - runtime_.

So for the following gradle project (same as example in https://github.com/kelemen/netbeans-gradle-project/issues/234), shouldn't `print.jar` be listed under `Dependencies - Compile for x` too? I've seen `Compile`, `Provided` and `Runtime` dependencies. What criteria drives the classification and listing of the dependencies under corresponding nodes? Or is this a bug?

```groovy
apply plugin: 'java'

repositories {
    mavenCentral()
}

sourceSets {
    x {
        compileClasspath += files("$buildDir/classes/main") { builtBy 'compileJava' }
        compileClasspath += files("lib/print.jar")
    }
}

dependencies {
    xCompile 'org.slf4j:slf4j-simple:1.7.12'
}
```


![image](https://cloud.githubusercontent.com/assets/790448/9518835/60c54ef2-4cba-11e5-8946-925b37b13fb7.png)


Apparently, if I add `print.jar` to the `runtimeClasspath` too, it is listed under `Compile for x` and there is no more `Provided` (agreeing with "provided = compile - runtime"):
```groovy
...
sourceSets.x.runtimeClasspath += files("lib/print.jar")
...
```
![image](https://cloud.githubusercontent.com/assets/790448/9518817/43fbb59a-4cba-11e5-9ab1-51434354227f.png)

**Comment by kelemen** [comment]
provided + compile is actually the compile time classpath (though some sourceset output directories are filtered for clarity and instead listed as a project dependencies). Provided dependencies has no meaning for Gradle, they are just separated for informational purposes. Also, note that the plugin does not use the list of dependencies displayed under the dependencies node for anything. Instead it relies on `compileClasspath` and `runtimeClasspath` explicitly.

**Comment by gallardo** [comment]
Thanks. For my own reference, the three dependency types:

```
apply plugin: 'java'

repositories {
    mavenCentral()
}

sourceSets {
    x {
        compileClasspath += files("lib/print.jar")
    }
}

dependencies {
    xCompile 'org.slf4j:slf4j-api:1.7.12'
    xRuntime 'org.slf4j:slf4j-simple:1.7.12'
}
```

![image](https://cloud.githubusercontent.com/assets/790448/9519358/53bc846a-4cbe-11e5-85e4-81d40e67c74c.png)

**Comment by gallardo** [comment]
Huhmm... I think I should include this last comment as part of the documentation...

**Comment by gallardo** [comment]
I'm afraid I completely missed https://github.com/kelemen/netbeans-gradle-project/wiki/Getting-Started#dependencies-node... :flushed:

**Comment by gallardo** [comment]
I'm making some progress here...

> At this moment it seems like I'm hitting a NetBeans bug but I'm neither sure, nor I know what the exact problem is
https://github.com/kelemen/netbeans-gradle-project/issues/193#issuecomment-135342439

With a better understanding of gradle and this plugin, it turns out that the build project declares some SourceSets justs for convenience. The properties of these source sets are used to configure other tasks (gwt compilation, packaging, installation), but the source sets themselves are neither compiled nor have a complete dependencies declaration. I'm opening a [feature request to filter them out of the project view](https://github.com/kelemen/netbeans-gradle-project/issues/235).
