### ISSUE TITLE
Composite builds?

### ISSUE THREAD

**Issue by hrstoyanov** [kelemen/netbeans-gradle-project#277]
@kelemen Any thoughts on the newly introduced "Composite Builds" in Gradle 2.13? I am starting to see the need for it. Here is how Hans explains it:
https://www.youtube.com/watch?v=vnmYcH4LSKk

**Comment by kelemen** [comment]
I was thinking about when they were talking about that feature it but I don't see how it would be possible to use that in NetBeans without any quirks. The reason is that in NB there is no "import project" the same way as in other IDEs. Projects just get auto loaded and I have no point in the code where I could reasonably supply multiple projects at once.

That said, there is a new option (not released yet) in the master branch which detects project dependencies based on the name of the jar file. This option can be used to achieve similar result (this option is disabled by default).

**Comment by hrstoyanov** [comment]
Thanks Attila,
I was more concern with having to install multiple modules to my local
Maven repo all the time during fast pace development: ./grades clean PTML X
Where X is one of many interdependent projects.

**Comment by kelemen** [comment]
Branch *composite_builds* should now provide appropriate support for composite builds. However, only if you defined them in your settings.gradle. I had big structural changes in that branch, so I will do some additional verification before merging it into master. However, there are no obvious bugs I have noticed, so I recommend trying it.

Since the feature is relatively new in Gradle, I don't know what could be considered as a best practice but this is what I do at the moment:

    def includeIfExist = { otherName ->
        def projectDir = mainDir.resolve(otherName)
        if (java.nio.file.Files.exists(projectDir)) {
            includeBuild projectDir
        }
    }

    includeIfExist 'project1'
    includeIfExist 'project2' 

That is check if other projects are there next to this project and if so, include them in the build.

**Comment by hrstoyanov** [comment]
@kelemen
Has this been released, if so, does it work with 3.3?

**Comment by kelemen** [comment]
It was merged into master but is not yet released. It should work with 3.3 but I have only tested it with 3.2

**Comment by entonio** [comment]
Hi. I've got the build process itself working, but I'm not sure what should be functional in terms of the UI itself.

I have sol-app which depends on sol-common, either via nexus or a local folder.

My sol-app `settings.gradle`:
```groovy
rootProject.name = 'sol-app'

// To include a local project, use e.g. -Psol-common=../../common/lib
def includeIfPossible = { locationVar ->
    try { includeBuild this."$locationVar" }
    catch (MissingPropertyException e) {
        println ":$locationVar NO-SOURCE, will use nexus"
    }
}

includeIfPossible 'sol-common'
```

The relevant parts of my sol-app `build.gradle`:
```groovy
project.group = 'org.example.sol' // this is also in sol-common
...
dependencies {
    compile group: 'org.example.sol', name: 'sol-common', version: '1.2.3'
}
```

The purpose of my method is not exactly the same as yours above:
- your `includeIfExist` will do `includeBuild` if the argument is a folder
- my `includeIfPossible` will do `includeBuild` if the argument is the name of a gradle command line parameter, whose value is then used as the folder

The build works, but code navigation and refactoring don't. Usages of the dependency are marked as errors in the editor until the project is closed and opened again. Clicking the identifiers will lead to the usual decompiled 'source' as if it were an external jar (which it is when not using `includeBuild`, of course).

Is this the way it has to be, or am I missing something?

)Since I'm defining `project.group`, I'm not adding groupId to publishing / publications / mavenJava, I wonder if that's correct.)

**Comment by entonio** [comment]
I'm using Gradle 3.5

**Comment by kelemen** [comment]
There is a known bug which is fixed in master. So, you can try building the plugin in master. If I remember correctly, the bug manifests if you don't already have the included project built (including its jars). And most likely I should have a patch release.

**Comment by entonio** [comment]
I've tried using the latest master and it does seem to reduce the red somewhat, but still far from ideal:

- Random files still get red on the project pane. Sometimes opening them will show red imports, other times there will be no error in the editor. All the red tends to disappear given some time, even though there's no indication that there's indexing going on.

- Navigation still leads to a decompiled jar instead of the dependency's project's source.

- Refactoring on the dependency ignores all the usages in the downstream project. This is unfortunate.

- Find usages DOES work, it shows results in both projects.

- Making changes in the dependency and then building the dependency and then building the downstream project DOES propagate the changes.

I don't know if these are NB limitations or whether I'm doing something wrong. I remember this kind of issue from when I started using (ant) dependency projects some 10 years ago, but I seem to recall it gradually went away. Maybe I'm wrong.

My build from master (`gradle build`) says `Version: 1.4.1.0.0.1` on NB.

Thanks for the dedication you've put into this plugin, it owes nothing to NB's core. I can't understand why they don't give it full support.

**Comment by kelemen** [comment]
- The red curlies I think are more likely to be an NB issue, though it is possible that I'm missing some change notification in some cases.
- I did not expect failures in go to sources. So, there is probably still something wrong but it seems to work for me. Can you create a sample project on GitHub reproducing your issue?
- I'm almost certain that refactoring fails for the same reason as go to sources.
- Building and everything like that simply execute Gradle commands, so I would certainly not expect that to fail, assuming no bug in Gradle.

Most people are ok with a separate plugin, so there was not much need to merge this plugin into the core. That said, once NB moving the Apache fully completes, it is possible that this plugin will be become part of the official NB release. There were some talk about this but there are some technical things to overcome (I still want to be able to have off-cycle release).

**Comment by entonio** [comment]
I think I've found the issue.

I've tried creating a 'lib' and 'app' projects from scratch, make 'app' include 'lib', and everything seemed to be working ok:
- I passed `-Plib=../lib` to gradle on the command line for the app project
- navigation worked
- refactoring worked
- Dependencies / Compile for main showed the other project nested inside (I'd never seen that)

Then I tried publishing the dependency to a repository:
- I closed and reopened and maybe cleaned 'app' (I don't recall)
- I did *not* pass `-Plib=../lib` to 'app'
- the 'lib' jar was fetched from the repository
- Dependencies / Compile for main began showing the 'lib' jar instead of the nested project
- refactoring and navigation broke

This wouldn't be strange, after all I'm using the jar now, but:
- Dependencies / Download sources didn't attach the lib sources (I'm not sure of this point because they may have not been properly uploaded, and I've since deleted the code for that)
- try as I may, I can't get back to the point I was before

So I suspect that having downloaded the jar once, the plugin loses the 'nested dependency' mode for good. I've tried all kinds of cleans and delete cache, but no luck.

I've uploaded the (now broken) projects to https://github.com/entonio/GradleComposite with all the files, even `.gradle/`, `.nb-gradle/` and `build/`.

('nexusPublic`will serve `nexusRelease` artifacts. I've deleted any personal info.)

**Comment by kelemen** [comment]
Thanks, I'll have a look at it tomorrow evening.

**Comment by kelemen** [comment]
I can't reproduce the issue. Where exactly provide this "-Plib" argument, so that NB knows about it? gradle.properties or in the global settings of NB?

If NB jumps to your dependency in the Gradle cache, then I'm almost certain, that you are not loading your project as a composite build (i.e., you do not call the `includeBuild` when NB loads your project).

It might be surprising but the plugin does not really treat composite builds and normal project dependencies different. The only reason why they do not always behave the same way is because originally, I chose a lazier way to handle project dependencies. After the composite build release, I tried to refactor it to treat them in a more approriate way. For your information, this is what happens in NB (roughly):

1. NB loads the project and queries the compile (and runtime) classpath of every source set (simply by calling say `sourceSets.main.compileClasspath`).
2. When NB try to navigate to a class, NB will ask the plugin: Who is the owner of this jar?
3. If the jar happens to be in a project directory (which is usually the case for the build outputs), then that project is the owner.
4. NB now asks the owner project: Where are the sources of this jar file?
5. If the project can answer where the sources are, then it must also tell NB if the sources are more important.
6. If the sources are more important, then NB will consider this as a project dependency and will rely on the source for code completion, rather than the built artifact.

The magic happens in step 4. There I try to map the jar file to the sources it was built from. There are some heuristic (which you can actually affect with some undocumented `ext` property) to determine what source roots are used by `Jar` tasks but the heurisitc is fine almost always (if this would be your problem, it would be completly deterministic and is probably not your problem).

Originally, I used to just replace *jar* dependencies with the output dirs of source sets, so I didn't have to make the mapping between jars and sources, only between the *classes* dir and the sources. So, any bug in composite build handling should be the result of me not refactoring the old replace *jar* files with *classes* dir properly.

Anyway, this means that if you see yourself jumping the jar in the Gradle cache, then Gradle did not provide the plugin with the jar output of the project but Gradle itself thought that you are using the artifact from the remote repository.

**Comment by entonio** [comment]
I've put the `Plib` either in NB's global settings or in the Built-in Tasks of the project properties. Either way seems to work the same.

Gradle does show the composite build in the log when using the parameter - it inserts the tasks from `lib` in `app`'s log - and will pick up the changes I make to 'lib' (which aren't published) -  as long as I build the 'lib' first, because the composite build in 'app' will always think 'lib's tasks are up-to-date unless I clean 'lib' (just making changes to it won't be noticed by the composite build of 'app').

If I find anything else I'll let you know.

**Comment by kelemen** [comment]
What happens for task execution doesn't really matter, the only thing what is relevant is what happens when NB evaluates the script. So, adding anything to the built-in tasks will not affect how NB sees your project (just that particular action). Though the global settings should be applied for model loading as well. It doesn't seem to be documented but I wonder how relative paths are resolved in `includeBuild` (I would assume its directory of *settings.gradle* but it seems to be undocumented). Does specifying absolute path helps? Or setting it outside of NB (in gradle.properites)?

**Comment by entonio** [comment]
I think the issue may be in your point 4 above.

When I put the property in the plugin settings, 'Script & tasks \ Gradle arguments',  NB does still show the jar instead of the project in the dependencies, but:
- it's shown in gray, and the tooltip says 'ignored' (navigation, however, goes to it)
- the jar is really the output of the other project, not some published version, I know it because I changed the name of the dependency locally and the jar name and contents changed accordingly (the new name isn't published anywhere)-

Is there any way I can debug this or influence the heuristics?

Using absolute paths seems to make no difference.

Setting it in properties is something I didn't want to do, because this is a setting to be used sometimes only, and only in development.

**Comment by kelemen** [comment]
The wiki page [Development](https://github.com/kelemen/netbeans-gradle-project/wiki/Development) describes how to setup the project for debugging.

If the project was set up, you can look at the following classes/methods (this model parsing is probably more complex than it should, so it might take some time to step through the code):

- `JavaExtensionDef.parseFromNewModels`: This converts the info read from Gradle into the model, the plugin uses (these models contains lazily initialized properties, so some of them won't be calculated right away).
- `GradleSourceForBinaryQuery`: This converts binary roots to source roots. So, probably this is good place to start.

If you could find the issue, that would be a great help and I would have a release immediately. Though, this might be the last release for NB 8.X because I'm currently working on the *nb9* branch which contains a lot of incompatible changes, so adding features to both of them would be considerable extra work.

**Comment by entonio** [comment]
I'll se what I can do, thank you!

**Comment by entonio** [comment]
Before I delve into it, there's one thing I forgot:

- The example projects I submitted here now seem to work fine. After reloading 'app', it switches between showing the jar or the other project in the Dependencies, according to whether I pass the gradle argument to it or not. I don't know what happened the other day, in which after switching to using the jar I couldn't get it back to using the project. Possibly something I was doing wrong.

- I've tried adding the sample 'lib' as a dependency to the real project I'm having issues with and Lo!, it also switches fine there, whereas the realLib does not (well, the realLib does switch from showing the jar to showing a grayed 'ignored' jar). This seems to pinpoint the problem to the realLib rather than the realApp, since the latter is including both lib and realLib in the exact same way.

- Now the difference:
  - lib is a 'normal' bare java lib, as you've been able to see
  - realLib has the following:
```groovy
apply plugin: 'org.springframework.boot'
bootRepackage {
    enabled = false
}
```
This was needed in order to be able to compile it, otherwise some springboot dependencies wouldn't be found (maybe there's another way, this was the easy option at the time). The build process for it shows `:bootRepackage SKIPPED`, which is as intended. This task does not of course exist in plain 'lib'.

(I'm sorry, but I've only noticed this difference now, or I would've checked it before.)

The reason I mention this is if by any chance you happen to know that some of this may be the reason NB won't use the project sources but the output jar instead. But I should mention I did try changing 'lib' to also use springboot, and it kept working fine as before, so maybe it's got nothing to do.

Personally I can't wait for NB9 :) And call me futile, but if only they refreshed the artwork...

**Comment by kelemen** [comment]
The content of the lib shouldn't matter. What could if the jar produced is not the output of the *jar* task. Or symlinks in paths can cause all kinds of misbehaviour.

The largest thread on the Apache NetBeans' mailing list is about what to have for the new splash screen, so you are probably not alone :)

**Comment by entonio** [comment]
I'VE FOUND IT!

My realLib had the following in its `build.gradle`:
```groovy
buildDir = "../_build/${rootProject.name}"
```

I did that at the time for some reasons, but apparently it breaks navigation. I've tried a number of combinations but it seems than leaving the default location will do (the default is `build`). Fortunately, this is something I can do.

As to why the jar was being shown as 'ignored', it's because it was inside a git-ignored path (`_build`).

Navigation and refactoring now work!
Now, if only they updated the icons (the green gradle project icon is actually nice). The splash screen I can live with ;)

**Comment by kelemen** [comment]
That seems to explain the issue: because of the "..", the owner project of the built artifact was wrong. I'm not sure I could easily fix that because it is relatively difficult to handle ownership in NB when the file is not in the project directory (it is not exactly impossible but can have some unwanted side effect). It is possible to at least make sure that every subproject knows about all the artifact - source mapping of all subprojects within the same build, however that is not top priority because it is a lot of extra work and almost never needed. Anyway, I'm glad you could find the root cause of the issue.

**Comment by entonio** [comment]
I've gladly changed them all to the default. The reasons they weren't no longer apply at this time, and I think this is something that can almost always be accommodated, so no need to invest time in it.

I'd just maybe include some note about it in some very visible place, this is something that may be rare but when it happens folks will be puzzled.

Thank you for all the patience in following this.
